### ISSUE TITLE
./node_modules/react-stl-viewer/lib/index.esm.js:3:0 Module not found: Can't resolve 'three'

### ISSUE THREAD

**Issue by hrqmonteiro** [GabrielMusat/react-stl-viewer#3]
![Screenshot from 2022-05-03 15-47-47](https://user-images.githubusercontent.com/17055027/166522023-094921ff-73be-49a4-9691-5552af337924.png)

And if i install `@types/three`, then i get:

```Error: Cannot find module '/home/minutrade/app-sls-lav/node_modules/three/examples/jsm/loaders/STLLoader'```

**Comment by GabrielMusat** [comment]
Keep in mind that `three` is a peer dependency, so you need to install it yourself in the same way you install the react package.

try `npm install three` if you are using npm, or `yarn add three` if you are using yarn.

**Comment by hrqmonteiro** [comment]
> Keep in mind that `three` is a peer dependency, so you need to install it yourself in the same way you install the react package.
> 
> Try `npm install three` if you are using npm, or `yarn add three` if you are using yarn.

That was the first thing i tried, i am still getting that error: `Error: Cannot find module '/home/minutrade/app-sls-lav/node_modules/three/examples/jsm/loaders/STLLoader'`

**Comment by GabrielMusat** [comment]
I am able to reproduce your problem if I install only the type definitions for three `yarn install @types/three`, but with three.js itself installed it works as expected `yarn install three`.
With this dependencies I am able to reproduce your problem, which is expected as  `three` is not installed:
```json
{
  "name": "react-stl-viewer-nextjs-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/three": "^0.140.0",
    "next": "12.1.6",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-stl-viewer": "^2.0.3"
  },
  "devDependencies": {
    "@types/node": "17.0.31",
    "@types/react": "18.0.8",
    "@types/react-dom": "18.0.3",
    "eslint": "8.14.0",
    "eslint-config-next": "12.1.6",
    "typescript": "4.6.4"
  }
```
With this other dependencies, the library works as expected:
```json
{
  "name": "react-stl-viewer-nextjs-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "three": "^0.140.0",
    "next": "12.1.6",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-stl-viewer": "^2.0.3"
  },
  "devDependencies": {
    "@types/node": "17.0.31",
    "@types/react": "18.0.8",
    "@types/react-dom": "18.0.3",
    "eslint": "8.14.0",
    "eslint-config-next": "12.1.6",
    "typescript": "4.6.4"
  }
}
```

**Comment by hrqmonteiro** [comment]
Here's my full package.json:

```
{
  "name": "app-sls-lav",
  "description": "app serverless",
  "private": true,
  "scripts": {
    "dev": "next dev",  
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "clean": "rimraf .next; rimraf .serverless; rimraf .serverless_nextjs",
    "format": "prettier --write .",
    "viewer": "npx tailwind-config-viewer -o",
    "type-check": "tsc --pretty --noEmit",
    "test": "yarn lint && yarn type-check && jest"
  },
  "engines": {
    "node": ">=14.x"
  },
  "dependencies": {
    "@capacitor/action-sheet": "^1.0.8",
    "@capacitor/core": "^3.4.1",
    "@capacitor/device": "^1.1.2",
    "@capacitor/geolocation": "^1.3.1",
    "@ffmpeg/core": "^0.10.0",
    "@ffmpeg/ffmpeg": "^0.10.1",
    "@ionic/pwa-elements": "^3.0.2",
    "@reach/portal": "^0.16.2",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.5.0",
    "@tailwindcss/line-clamp": "^0.3.1",
    "@tailwindcss/ui": "^0.7.2",
    "aws-amplify": "^4.3.13",
    "aws-amplify-react": "^5.1.9",
    "axios": "^0.26.0",
    "body-scroll-lock": "^4.0.0-beta.0",
    "bunyan": "^1.8.15",
    "bunyan-prettystream": "^0.1.3",
    "classnames": "^2.3.1",
    "daisyui": "^2.11.0",
    "date-fns": "^2.28.0",
    "email-validator": "^2.0.4",
    "keen-slider": "^6.6.3",
    "lodash.throttle": "^4.1.1",
    "moment": "^2.29.1",
    "next": "11",
    "next-pwa": "^5.4.6",
    "next-seo": "^5.1.0",
    "next-themes": "^0.1.1",
    "nextjs-progressbar": "^0.0.14",
    "nodemailer": "^6.7.1",
    "papaparse": "^5.3.2",
    "react": "^17.0.2",
    "react-dnd": "^15.1.1",
    "react-dnd-html5-backend": "^15.1.2",
    "react-dom": "^17.0.2",
    "react-dropzone": "^12.0.4",
    "react-hook-form": "^7.28.0",
    "react-icons": "^4.3.1",
    "react-infinite-scroll-component": "^6.1.0",
    "react-input-color": "^4.0.0",
    "react-masonry-css": "^1.0.16",
    "react-merge-refs": "^1.1.0",
    "react-modal": "^3.14.4",
    "react-phone-number-input": "^3.1.47",
    "react-qr-code": "^2.0.3",
    "react-scroll-parallax": "^3.0.5",
    "react-stl-viewer": "^2.0.3",
    "react-tag-input": "^6.7.3",
    "react-ticker": "^1.2.2",
    "react-to-print": "^2.14.4",
    "react-toast": "^1.0.3",
    "react-top-loading-bar": "^2.0.1",
    "react-use": "^17.3.2",
    "recharts": "^2.1.9",
    "suneditor": "^2.42.0",
    "suneditor-react": "^3.4.0",
    "tabbable": "^5.2.1",
    "three": "^0.140.0",
    "unsplash-js": "^7.0.15",
    "use-debounce": "^7.0.1",
    "uuid": "^8.3.2",
    "video.js": "^7.18.1",
    "videojs-react-enhanced": "^0.3.1"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.2",
    "@types/body-scroll-lock": "^3.1.0",
    "@types/bunyan": "^1.8.8",
    "@types/bunyan-prettystream": "^0.1.32",
    "@types/lodash.throttle": "^4.1.6",
    "@types/node": "^17.0.19",
    "@types/papaparse": "^5.3.2",
    "@types/react": "^17.0.41",
    "@types/react-beforeunload": "^2.1.1",
    "@types/react-dom": "^17.0.14",
    "@types/react-modal": "^3.13.1",
    "@types/react-phone-number-input": "^3.0.13",
    "@types/react-tag-input": "^6.1.3",
    "@types/uuid": "^8.3.1",
    "@types/video.js": "^7.3.32",
    "autoprefixer": "^10.4.4",
    "eslint": "^8.11.0",
    "eslint-config-next": "12.1.0",
    "opus-media-recorder": "^0.8.0",
    "postcss": "^8.4.12",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-import": "^14.0.2",
    "postcss-nesting": "^10.0.3",
    "postcss-preset-env": "^7.4.1",
    "prettier": "^2.6.0",
    "tailwindcss": "^3.0.23",
    "typescript": "^4.5.5",
    "webpack": "^5.69.1"
  }
}
```

It doesn't work.

![Screenshot from 2022-05-04 16-55-53](https://user-images.githubusercontent.com/17055027/166815607-19a21860-5064-4acf-b32b-90e26fe87945.png)

And on my terminal, when i do `yarn dev` i get this errors:

```
info  - ready on http://localhost:3000
The schema has already been initialized
Error: Cannot find module '/home/minutrade/app-sls-lav/node_modules/three/examples/jsm/loaders/STLLoader'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:916:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:909:15)
    at resolveExports (internal/modules/cjs/loader.js:449:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.mod._resolveFilename (/home/minutrade/app-sls-lav/node_modules/next/dist/build/webpack/require-hook.js:96:28)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/minutrade/app-sls-lav/node_modules/react-stl-viewer/lib/index.js:7:17) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/minutrade/app-sls-lav/node_modules/three/package.json'
}
error - Error: Cannot find module '/home/minutrade/app-sls-lav/node_modules/three/examples/jsm/loaders/STLLoader'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:916:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:909:15)
    at resolveExports (internal/modules/cjs/loader.js:449:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.mod._resolveFilename (/home/minutrade/app-sls-lav/node_modules/next/dist/build/webpack/require-hook.js:96:28)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/minutrade/app-sls-lav/node_modules/react-stl-viewer/lib/index.js:7:17) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/minutrade/app-sls-lav/node_modules/three/package.json',
  page: '/report'
}
Error: Cannot find module '/home/minutrade/app-sls-lav/node_modules/three/examples/jsm/loaders/STLLoader'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:916:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:909:15)
    at resolveExports (internal/modules/cjs/loader.js:449:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.mod._resolveFilename (/home/minutrade/app-sls-lav/node_modules/next/dist/build/webpack/require-hook.js:96:28)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/minutrade/app-sls-lav/node_modules/react-stl-viewer/lib/index.js:7:17) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/minutrade/app-sls-lav/node_modules/three/package.json'
}
```

**Comment by GabrielMusat** [comment]
True, I am able to replicate now. This is related to how three.js is exposing the examples folder, which seems unbundled and with es6 exports, thats why next is having problems importing it with SSR. see https://discourse.threejs.org/t/can-not-load-gltfloader-in-nextjs-application/12317/17 for more info.

Luckily there is already a solution to this, will be fixed soon

**Comment by GabrielMusat** [comment]
solved in version 2.0.4.

**Comment by rmartin177** [comment]
i dont know if i have exactly the same problem, this is my error 
![image](https://user-images.githubusercontent.com/34422739/187806911-31a9d8f6-0629-43ec-8947-9c7382c5cdc8.png)
and this my package.json, i am using next.js without typescript and i have install three and react-stl-viewer

{
  "name": "example",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.2.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-stl-viewer": "^2.1.2",
    "three": "^0.144.0"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.8",
    "eslint": "8.23.0",
    "eslint-config-next": "12.2.5",
    "postcss": "^8.4.16",
    "tailwindcss": "^3.1.8"
  }
}

**Comment by gabotechs** [comment]
I see that this is a issue with bundling one of the dependencies https://github.com/pmndrs/drei/issues/747
